
spring:
  security:
  datasource :
    url : jdbc:h2:./data/SMRP
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test